### ISSUE TITLE
Java 7 cask doesn't seem to exist any more

### ISSUE THREAD

**Issue by robfletcher** [DanielThomas/dotfiles#1]
I get an error installing Java 7 and indeed running `brew cask install java7` myself results in `Error: No available Cask for java7`

**Comment by DanielThomas** [comment]
I've long since moved to Zulu, and I'm currently only installing 7 on x86_64:
```
dev/install.homebrew-cask.x86_64-native
2:zulu7
```

```
dev/install.homebrew-cask
2:zulu
3:zulu8
4:zulu11
5:zulu13
6:zulu15
```
